# Generated by Django 3.0.1 on 2020-01-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='X')),
                ('y', models.FloatField(verbose_name='Y')),
                ('n', models.IntegerField(verbose_name='Number of points')),
                ('operation_type', models.IntegerField(choices=[(1, 'Nearest'), (2, 'Furthest')], default=1)),
            ],
            options={
                'verbose_name': 'history',
                'verbose_name_plural': 'historys',
            },
        ),
    ]
