# Generated by Django 3.0.1 on 2020-01-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefernceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(verbose_name='ID')),
                ('x', models.FloatField(verbose_name='X')),
                ('y', models.FloatField(verbose_name='Y')),
            ],
            options={
                'verbose_name': 'referncetable',
                'verbose_name_plural': 'referncetable',
            },
        ),
    ]
