# Generated by Django 3.0.1 on 2020-01-05 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_referncetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_points', models.IntegerField(verbose_name='NO. Points')),
                ('points_list', models.CharField(max_length=50, verbose_name='Points List')),
            ],
            options={
                'verbose_name': 'result',
                'verbose_name_plural': 'results',
            },
        ),
        migrations.AddField(
            model_name='history',
            name='result_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='points.Result'),
        ),
    ]
